ALTER TABLE products
  ADD COLUMN IF NOT EXISTS consumption_amount NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS consumption_period TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_consumption_date TEXT DEFAULT NULL;
